#!/usr/bin/env python3
"""Regenerate the 1-bit glyph atlas used by the matrix rain screensaver."""

from __future__ import annotations

import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_BDF = (
    REPO_ROOT
    / "third_party"
    / "fusion-pixel-font"
    / "10px-proportional"
    / "fusion-pixel-10px-proportional-ja.bdf"
)
OUTPUT_HEADER = REPO_ROOT / "src" / "fonts" / "MatrixGlyphAtlas.h"

CELL_WIDTH = 8
CELL_HEIGHT = 12
BASELINE = 10  # rows from the cell top down to the glyph baseline

# Digits, capital Latin letters, and half-width katakana. Half-width kana are
# the ones the film used, and their 1:2 box is what fits an 8x12 cell without
# squashing -- full-width kana are square and would have to be scaled down.
CODEPOINT_RANGES = (
    (0x30, 0x39),  # 0-9
    (0x41, 0x5A),  # A-Z
    (0xFF66, 0xFF9D),  # half-width katakana, excluding the voiced sound marks
)


def parse_bdf(path: Path) -> dict[int, tuple[tuple[int, int, int, int], list[str]]]:
    """Return {codepoint: ((width, height, xOffset, yOffset), hex rows)}."""
    glyphs: dict[int, tuple[tuple[int, int, int, int], list[str]]] = {}
    codepoint: int | None = None
    box: tuple[int, int, int, int] | None = None
    rows: list[str] = []
    in_bitmap = False
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("STARTCHAR"):
            codepoint, box, rows, in_bitmap = None, None, [], False
        elif line.startswith("ENCODING"):
            codepoint = int(line.split()[1])
        elif line.startswith("BBX"):
            width, height, x_offset, y_offset = map(int, line.split()[1:5])
            box = (width, height, x_offset, y_offset)
        elif line.startswith("BITMAP"):
            in_bitmap = True
        elif line.startswith("ENDCHAR"):
            if codepoint is not None and codepoint >= 0 and box is not None:
                glyphs[codepoint] = (box, rows)
            codepoint, box, rows, in_bitmap = None, None, [], False
        elif in_bitmap:
            rows.append(line.strip())
    return glyphs


def rasterize(box: tuple[int, int, int, int], rows: list[str]) -> list[int]:
    """Center a BDF glyph in the cell and pack each row into one byte."""
    width, height, _, y_offset = box
    cell = [0] * CELL_HEIGHT
    left = (CELL_WIDTH - width) // 2
    top = BASELINE - height - y_offset
    for source_y, row in enumerate(rows):
        if not row:
            continue
        bits = bin(int(row, 16))[2:].zfill(len(row) * 4)[:width]
        y = top + source_y
        if not 0 <= y < CELL_HEIGHT:
            continue
        packed = 0
        for source_x, bit in enumerate(bits):
            x = left + source_x
            if bit == "1" and 0 <= x < CELL_WIDTH:
                packed |= 0x80 >> x
        cell[y] |= packed
    return cell


def selected_codepoints() -> list[int]:
    return [cp for first, last in CODEPOINT_RANGES for cp in range(first, last + 1)]


def render_header(atlas: list[tuple[int, list[int]]]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Generated by fonts/generate_matrix_atlas.py -- do not edit by hand.",
        "// Source: Fusion Pixel Font 10px proportional (ja), OFL-1.1.",
        "//",
        f"// {len(atlas)} glyphs, one byte per row, most significant bit leftmost.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace fonts {",
        "",
        f"    constexpr uint8_t kMatrixGlyphWidth = {CELL_WIDTH};",
        f"    constexpr uint8_t kMatrixGlyphHeight = {CELL_HEIGHT};",
        f"    constexpr uint8_t kMatrixGlyphCount = {len(atlas)};",
        f"    constexpr size_t kMatrixGlyphStride = {CELL_HEIGHT};",
        "",
        "    inline constexpr uint8_t kMatrixGlyphBitmaps[] = {",
    ]
    for codepoint, cell in atlas:
        body = " ".join(f"0x{value:02X}," for value in cell)
        lines.append(f"        {body} // U+{codepoint:04X}")
    lines += [
        "    };",
        "",
        "    static_assert(sizeof(kMatrixGlyphBitmaps) == "
        "static_cast<size_t>(kMatrixGlyphCount) * kMatrixGlyphStride);",
        "",
        "} // namespace fonts",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the header is stale")
    arguments = parser.parse_args()

    glyphs = parse_bdf(SOURCE_BDF)
    atlas: list[tuple[int, list[int]]] = []
    missing: list[int] = []
    for codepoint in selected_codepoints():
        entry = glyphs.get(codepoint)
        if entry is None:
            missing.append(codepoint)
            continue
        atlas.append((codepoint, rasterize(*entry)))
    if missing:
        formatted = ", ".join(f"U+{cp:04X}" for cp in missing)
        raise SystemExit(f"source font is missing {len(missing)} glyphs: {formatted}")
    if len(atlas) > 255:
        raise SystemExit(f"atlas holds {len(atlas)} glyphs; the cell glyph index is a uint8_t")

    header = render_header(atlas)
    if arguments.check:
        current = OUTPUT_HEADER.read_text(encoding="utf-8") if OUTPUT_HEADER.exists() else ""
        if current != header:
            raise SystemExit(f"{OUTPUT_HEADER.relative_to(REPO_ROOT)} is stale; rerun without --check")
        print(f"{OUTPUT_HEADER.relative_to(REPO_ROOT)} is up to date")
        return 0

    OUTPUT_HEADER.write_text(header, encoding="utf-8")
    print(
        f"wrote {OUTPUT_HEADER.relative_to(REPO_ROOT)} "
        f"({len(atlas)} glyphs, {len(atlas) * CELL_HEIGHT} bytes)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
